### ISSUE TITLE
Where can I download 'firefox' databse?

### ISSUE THREAD

**Issue by zxch3n** [hscrocha/NextBug-REP-Comparative-Study-Impl#1]
I'm new to this area. I'm interested in your work and try to use this tool.

But it requires a 'firefox' database. So when I ran this program it threw `Unknown database 'firefox'`. So does the 'mylyn' database.

Where can I download these databases? / How can I create these databases?

Thanks!

**Comment by hscrocha** [comment]
Hello. Due to legal constraints, I cannot share bug databases that belong to other products/companies. 

The "firefox" database is a custom version of the database used by bugzilla. More specifically, that database used the data from here <[https://bugzilla.mozilla.org/](https://bugzilla.mozilla.org/)>.

Now the Mylyn database was never used for this particurlar experiment. I just left the code there by mistake. 

The actual algorithm can be found on my paper published at SANER 2016, I can send you the paper if you want.

**Comment by hscrocha** [comment]
Another important clarification is that this repository is not "a tool". This repository is to share the code I used for the experiments described in the SANER 2016 paper. It was never designed to be a stand-alone "tool". I don't even remember if there is an interface or if every test is hardcoded.

If you are looking for a tool then you should get "NextBug", which was specifically designed to be an addon for Bugzilla. <[https://github.com/aserg-ufmg/NextBug](https://github.com/aserg-ufmg/NextBug)>

**Comment by zxch3n** [comment]
Many thanks for the prompt reply!

I read your paper before I visited this repo actually 😄. And I was trying to reproduce the experiments' results.   I wonder whether I may use the "NextBug" tool repo (aserg-ufmg/NextBug) to do it. Would that be more convenient? 

I couldn't find any link that leads to the bug data download page in the website <https://bugzilla.mozilla.org/> 😟 Did you use a web crawler to collect this data?

**Comment by hscrocha** [comment]
The NextBug repo is a complete addon for Bugzilla. The algorithm there should be the same. However, there is no REP implementation in NextBug repo --- that is the reason for this Java implementation, to perform a comparative study.

Just be aware that the standard Bugzilla database is not exactly the same as the Mozilla one. The Mozilla added some custom fields to a few tables. However, the table structure and relations are the same.

When I started the experiment (around 4 years ago), there was a place where you could ask Mozilla for their data. I got a database dump directly from them (which unfortunately I don't have the liberty to share it). After a while, they took that out. Most researchers that I know are crawling the data themselves to circumvent this issue.

**Comment by zxch3n** [comment]
Thanks! I guess I should just use another repo then and find a way to deal with the data.
